# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Challenge3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Challenge3
  
  # KMM shared modules
  pod 'KMPNativeCoroutinesCombine', '0.7.0'
  pod 'shared', :path => '../shared'

end
